### ISSUE TITLE
TypeError: Cannot read property 'sameAs' of undefined

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-same-as#4]
Possibly an issue with ssb-friends@3?

```console
$ npm ls ssb-friends
patchbay@7.15.6 /home/christianbundy/src/ssbc/patchbay
├─┬ ssb-chess-mithril@1.0.7
│ ├─┬ patchcore@1.28.3
│ │ └── ssb-friends@2.4.0 
│ └─┬ ssb-chess@3.1.4
│   └─┬ patchcore@1.28.3
│     └── ssb-friends@2.4.0 
├── ssb-friends@3.1.12 
├─┬ ssb-same-as@0.0.0 (github:ssbc/ssb-same-as#4467dd3da6c18b8dcef628ad6c6c526cfca35eea)
│ └── ssb-friends@2.4.0 
└─┬ ssb-server@13.5.2
  └── ssb-friends@3.1.12  deduped
```

```js
sbot.sameAs.get('@+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519', (err, val) => {
  if (err) throw err
  console.log(val)
})
```

```
TypeError: Cannot read property 'sameAs' of undefined
    at Object.require.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use.use (/home/christianbundy/src/ssbc/patchbay/server.js:32:10)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/secret-stack/api.js:43:28
    at Array.forEach (<anonymous>)
    at create (/home/christianbundy/src/ssbc/patchbay/node_modules/secret-stack/api.js:42:20)
    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchbay/server.js:45:12)
    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchbay/server.js:50:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
```

**Comment by christianbundy** [comment]
cc: @mmckegg, any idea on what might have broken here?
